spring:
  application:
    name: demo

  ai:
    chat:
      client:
        observations:
          include-input: true
      observations:
        include-completion: true
        include-prompt: true
    ollama:
      chat:
        options:
          model: qwen2.5
          num-ctx: 4096
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      observations:
        include-query-response: true
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
