spring:
  application:
    name: demo
  http:
    client:
      connect-timeout: 60s
      read-timeout: 60s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      service.name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    logging:
      endpoint: "http://localhost:4318/v1/logs"
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
