spring:
  main:
    web-application-type: none
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          additional-models:
            - llava-phi3
        embedding:
          include: false
      chat:
        options:
          model: llama3.2
